name: mega_cut
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  file_picker: any
  permission_handler: any
  ffmpeg_kit_flutter_new: ^4.1.0
  video_player: any
  audio_waveforms: any
  just_audio: any
  path_provider: any
  share_plus: any
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
